version: '3'
services:
  db:
    image: postgres:12.7
    container_name: horas_db
    restart: always
    environment:
      POSTGRES_PASSWORD: password

  web:
    container_name: horas
    build: .
    command: serve
    env_file:
      - .env
    entrypoint: /usr/src/app/entrypoint-dev.sh
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
