name: CI
env:
  DJANGO_SECRET_KEY: "SecretKeyForCI"
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel

      - name: Cache pipenv
        id: cache-pipenv
        uses: actions/cache@v2
        with:
          path: ~/.local/share/virtualenvs
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

      - name: Install Python dependencies
        if: steps.cache-pipenv.outputs.cache-hit != 'true'
        run: |
          pipenv install --dev

      - name: Lint with black
        run: pipenv run black --check .

      - name: Lint with flake8
        run: pipenv run flake8 horas --ignore=E501

      - name: Test
        run: pipenv run python manage.py test --configuration=Testing --verbosity=3 --noinput
